export const fonts = {
    ComfortaBold: 'Comfortaa-Bold',
    ComfortaLight: 'Comfortaa-Light',
    ComfortaMedium: 'Comfortaa-Medium',
    ComfortaRegular: 'Comfortaa-Regular',
    ComfortaSemi: 'Comfortaa-SemiBold',
    MontserratBlack: 'Montserrat-Black',
    MontserratBlackItalic: 'Montserrat-BlackItalic',
    MontserratBold: 'Montserrat-Bold',
    MontserratBoldItalic: 'Montserrat-BoldItalic',
    MontserratExtra: 'Montserrat-ExtraBold',
    MontserratExtraBoldItalic: 'Montserrat-ExtraBoldItalic',
    MontserratExtraLight: 'Montserrat-ExtraLight',
    MontserratExtraLightItalic: 'Montserrat-ExtraLightItalic',
    MontserratItalic: 'Montserrat-Italic',
    MontserratLight: 'Montserrat-Light',
    MontserratLightItalic: 'Montserrat-LightItalic',
    MontserratMedium: 'Montserrat-Medium',
    MontserratMediumItalic: 'Montserrat-MediumItalic',
    MontserratRegular: 'Montserrat-Regular',
    MontserratSemi: 'Montserrat-SemiBold',
    MontserratSemiItalic: 'Montserrat-SemiItalic',
    MontserratThin: 'Montserrat-Thin',
    MontserratThinItalic: 'Montserrat-ThinItalic',

}